2022-08-04 01:18:08,222 - my_test.py[line:10] - ERROR: test error
2022-08-04 13:25:35,353 - twitter_url_visit.py[line:131] - ERROR: 'module' object is not callable
2022-08-04 13:26:14,125 - twitter_url_visit.py[line:132] - ERROR: 'module' object is not callable
2022-08-04 13:26:46,855 - twitter_url_visit.py[line:131] - ERROR: HTTPSConnectionPool(host='madison.com', port=443): Max retries exceeded with url: /news/national/griners-moscow-trial-resumes-uks-boris-johnson-to-resign-nadal-weighs-wimbledon-exit/article_90620ee1-4f1a-50de-836b-fe91ff69caaf.html?utm_campaign=snd-autopilot&utm_medium=social&utm_source=twitter_WiStateJournal (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2022-08-04 13:27:59,734 - twitter_url_visit.py[line:131] - ERROR: list index out of range
2022-08-04 15:53:54,411 - twitter_url_visit.py[line:183] - ERROR: HTTPSConnectionPool(host='wcfcourier.com', port=443): Max retries exceeded with url: /news/national/griners-moscow-trial-resumes-uks-boris-johnson-to-resign-nadal-weighs-wimbledon-exit/article_7cf898d7-799d-5b8e-af1c-b20704de6ed2.html?utm_campaign=snd-autopilot&utm_medium=social&utm_source=twitter_wcfcourier (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2022-08-04 16:03:02,272 - twitter_url_visit.py[line:163] - ERROR: HTTPSConnectionPool(host='pantagraph.com', port=443): Max retries exceeded with url: /news/national/griners-moscow-trial-resumes-uks-boris-johnson-to-resign-nadal-weighs-wimbledon-exit/article_65ef1ebc-950b-5ae3-8e3c-0356df8f5947.html?utm_campaign=snd-autopilot&utm_medium=social&utm_source=twitter_Pantagraph (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2022-08-04 16:03:12,296 - twitter_url_visit.py[line:163] - ERROR: HTTPSConnectionPool(host='dailyjournalonline.com', port=443): Max retries exceeded with url: /news/national/griners-moscow-trial-resumes-uks-boris-johnson-to-resign-nadal-weighs-wimbledon-exit/article_637278d7-d8b5-53d6-9f47-e3686bfb4c9b.html?utm_campaign=blox&utm_source=twitter&utm_medium=social (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2022-08-04 16:03:22,337 - twitter_url_visit.py[line:163] - ERROR: HTTPSConnectionPool(host='journaltimes.com', port=443): Max retries exceeded with url: /news/national/griners-moscow-trial-resumes-uks-boris-johnson-to-resign-nadal-weighs-wimbledon-exit/article_eaedc476-1b82-55f3-8409-942292c02103.html?utm_campaign=snd-autopilot&utm_medium=social&utm_source=twitter_Journaltimes (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2022-08-04 16:03:32,355 - twitter_url_visit.py[line:163] - ERROR: HTTPSConnectionPool(host='hubs.li', port=443): Max retries exceeded with url: /Q01fRNk70 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2022-08-04 16:03:42,378 - twitter_url_visit.py[line:163] - ERROR: HTTPConnectionPool(host='127.0.0.1', port=1080): Read timed out. (read timeout=10)
2022-08-04 16:03:52,395 - twitter_url_visit.py[line:163] - ERROR: HTTPSConnectionPool(host='bit.ly', port=443): Max retries exceeded with url: /3y2WPhd (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2022-08-04 16:04:49,696 - twitter_url_visit.py[line:186] - ERROR: could not broadcast input array from shape (3,) into shape (4,)
2022-08-04 16:56:01,690 - twitter_url_visit.py[line:179] - ERROR: could not broadcast input array from shape (3,) into shape (4,)
2022-08-04 16:57:05,576 - twitter_url_visit.py[line:179] - ERROR: Must have equal len keys and value when setting with an iterable
2022-08-04 17:52:25,422 - twitter_url_visit.py[line:158] - ERROR: HTTPSConnectionPool(host='wcfcourier.com', port=443): Max retries exceeded with url: /news/national/griners-moscow-trial-resumes-uks-boris-johnson-to-resign-nadal-weighs-wimbledon-exit/article_7cf898d7-799d-5b8e-af1c-b20704de6ed2.html?utm_campaign=snd-autopilot&utm_medium=social&utm_source=twitter_wcfcourier (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F2B53903A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2022-08-04 17:52:51,484 - twitter_url_visit.py[line:158] - ERROR: HTTPSConnectionPool(host='wcfcourier.com', port=443): Max retries exceeded with url: /news/national/griners-moscow-trial-resumes-uks-boris-johnson-to-resign-nadal-weighs-wimbledon-exit/article_7cf898d7-799d-5b8e-af1c-b20704de6ed2.html?utm_campaign=snd-autopilot&utm_medium=social&utm_source=twitter_wcfcourier (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002B521B0F610>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2022-08-04 17:53:50,998 - twitter_url_visit.py[line:158] - ERROR: HTTPConnectionPool(host='127.0.0.1', port=1080): Max retries exceeded with url: http://dlvr.it/STsWcS (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D971AC4B50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
